apiVersion: v1
kind: Service
metadata:
  name: pixelstreaming-service__NUMBER__
spec:
  ports:
    - nodePort: __NODE_PORT__
      port: __PORT__
      targetPort: 80
  selector:
    app: pixel-streaming__NUMBER__
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelstreaming-deployment__NUMBER__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixel-streaming__NUMBER__
  template:
    metadata:
      labels:
        app: pixel-streaming__NUMBER__
    spec:
      containers:
        - image: __ACCOUNT_ID__.dkr.ecr.__REGION__.amazonaws.com/pixel-streaming:latest
          name: pixel-streaming
          resources:
            limits:
              nvidia.com/gpu: 2
          env:
            - name: RES_X
              value: "1280"
            - name: RES_Y
              value: "720"
        - image: __ACCOUNT_ID__.dkr.ecr.__REGION__.amazonaws.com/signalling-server:latest
          name: signalling-server
          ports:
            - containerPort: 80
---
